services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./apps/backend:/app
    depends_on:
      - mock-vector-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  mock-vector-db:
    image: nginxdemos/hello
    ports:
      - "8100:8100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100"]
      interval: 30s
      timeout: 5s
      retries: 3
  customer-bot:
    build: ./apps/customer-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./apps/customer-bot:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
  agent-copilot:
    build: ./apps/agent-copilot
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./apps/agent-copilot:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
