version: '3.8'
services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./apps/backend:/app
    depends_on:
      - pinecone
  pinecone:
    image: pinecone/local
    ports:
      - "8100:8100"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
  customer-bot:
    build: ./apps/customer-bot
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ./apps/customer-bot:/app
  agent-copilot:
    build: ./apps/agent-copilot
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    volumes:
      - ./apps/agent-copilot:/app
